version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: al4izzy/foodgram_backend
    container_name: foodgram-backend
    env_file: ../.env
    volumes:
      - static:/app/collected_static
      - media:/app/collected_media
    depends_on:
      - db
  frontend:
    env_file: ../.env
    image: al4izzy/foodgram_frontend
    container_name: foodgram-front
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "9080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media/

